name: Deploy

on:
  workflow_run:
    workflows: ["test"] 
    types:
      - completed
    
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Log in AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
    
    - name: CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name Deploy \
          --deployment-group-name TOMCAT \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
